Document: dirt
Title: Debian dirt Manual
Author: <insert document author here>
Abstract: This manual describes what dirt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dirt/dirt.sgml.gz

Format: postscript
Files: /usr/share/doc/dirt/dirt.ps.gz

Format: text
Files: /usr/share/doc/dirt/dirt.text.gz

Format: HTML
Index: /usr/share/doc/dirt/html/index.html
Files: /usr/share/doc/dirt/html/*.html
